---
- hosts: all
- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: all
- name: Delete wireshark
  import_playbook: ../static-assignments/common-del.yml


- hosts: webserver
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: lb
- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required